
plugins:
  - jemoji
  
title: elisavazz.github.io
description: > # this means to ignore newlines until "baseurl:"
website
repository: https://github.com/elisavazz
#baseurl: /me  # the subpath of your site, e.g. /blog
url: http://elisavazz.github.io/  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: elisavazz

navigation:
  - text: Home
    url: /
  - text: Projects
    url: /projects

social:
  - service: wordpress
    username: elisavazz
    link: https://elisavazz.wordpress.com/

# Plugins
gems:
- jekyll-seo-tag

